[package]
name = "cargo"
version = "0.1.0"
authors = ["kahzerx <kahzer123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]  # This is where you load your dependencies. https://crates.io
log = "0.4.11"
